/* 
 * Wire4RestAPI
 *
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using MX.Wire4.Client;
using MX.Wire4.Model;

namespace MX.Wire4.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IComprobanteElectrnicoDePagoCEPApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Consulta de CEP
        /// </summary>
        /// <remarks>
        /// Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </remarks>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>CepResponse</returns>
        CepResponse ObtainTransactionCepUsingPOST (CepSearchBanxico body, string authorization);

        /// <summary>
        /// Consulta de CEP
        /// </summary>
        /// <remarks>
        /// Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </remarks>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>ApiResponse of CepResponse</returns>
        ApiResponse<CepResponse> ObtainTransactionCepUsingPOSTWithHttpInfo (CepSearchBanxico body, string authorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Consulta de CEP
        /// </summary>
        /// <remarks>
        /// Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </remarks>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>Task of CepResponse</returns>
        System.Threading.Tasks.Task<CepResponse> ObtainTransactionCepUsingPOSTAsync (CepSearchBanxico body, string authorization);

        /// <summary>
        /// Consulta de CEP
        /// </summary>
        /// <remarks>
        /// Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </remarks>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>Task of ApiResponse (CepResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CepResponse>> ObtainTransactionCepUsingPOSTAsyncWithHttpInfo (CepSearchBanxico body, string authorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ComprobanteElectrnicoDePagoCEPApi : IComprobanteElectrnicoDePagoCEPApi
    {
        private MX.Wire4.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ComprobanteElectrnicoDePagoCEPApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ComprobanteElectrnicoDePagoCEPApi(String basePath)
        {
            this.Configuration = new MX.Wire4.Client.Configuration { BasePath = basePath };

            ExceptionFactory = MX.Wire4.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComprobanteElectrnicoDePagoCEPApi"/> class
        /// </summary>
        /// <returns></returns>
        public ComprobanteElectrnicoDePagoCEPApi()
        {
            this.Configuration = MX.Wire4.Client.Configuration.Default;

            ExceptionFactory = MX.Wire4.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComprobanteElectrnicoDePagoCEPApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ComprobanteElectrnicoDePagoCEPApi(MX.Wire4.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = MX.Wire4.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = MX.Wire4.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MX.Wire4.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MX.Wire4.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Consulta de CEP Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </summary>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>CepResponse</returns>
        public CepResponse ObtainTransactionCepUsingPOST (CepSearchBanxico body, string authorization)
        {
             ApiResponse<CepResponse> localVarResponse = ObtainTransactionCepUsingPOSTWithHttpInfo(body, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Consulta de CEP Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </summary>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>ApiResponse of CepResponse</returns>
        public ApiResponse< CepResponse > ObtainTransactionCepUsingPOSTWithHttpInfo (CepSearchBanxico body, string authorization)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ComprobanteElectrnicoDePagoCEPApi->ObtainTransactionCepUsingPOST");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ComprobanteElectrnicoDePagoCEPApi->ObtainTransactionCepUsingPOST");

            var localVarPath = "/ceps";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ObtainTransactionCepUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CepResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CepResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CepResponse)));
        }

        /// <summary>
        /// Consulta de CEP Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </summary>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>Task of CepResponse</returns>
        public async System.Threading.Tasks.Task<CepResponse> ObtainTransactionCepUsingPOSTAsync (CepSearchBanxico body, string authorization)
        {
             ApiResponse<CepResponse> localVarResponse = await ObtainTransactionCepUsingPOSTAsyncWithHttpInfo(body, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Consulta de CEP Consulta el CEP de un pago realizado a través del SPEI, si es que este se encuentra disponible en BANXICO.
        /// </summary>
        /// <exception cref="MX.Wire4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Información para buscar un CEP</param>
        /// <param name="authorization">Header para token</param>
        /// <returns>Task of ApiResponse (CepResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CepResponse>> ObtainTransactionCepUsingPOSTAsyncWithHttpInfo (CepSearchBanxico body, string authorization)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ComprobanteElectrnicoDePagoCEPApi->ObtainTransactionCepUsingPOST");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ComprobanteElectrnicoDePagoCEPApi->ObtainTransactionCepUsingPOST");

            var localVarPath = "/ceps";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ObtainTransactionCepUsingPOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CepResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CepResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CepResponse)));
        }

    }
}
