/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTests
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Test]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Account
            //Assert.IsInstanceOfType<Account> (instance, "variable 'instance' is a Account");
        }


        /// <summary>
        /// Test the property 'AmountLimit'
        /// </summary>
        [Test]
        public void AmountLimitTest()
        {
            // TODO unit test for the property 'AmountLimit'
        }
        /// <summary>
        /// Test the property 'BankKey'
        /// </summary>
        [Test]
        public void BankKeyTest()
        {
            // TODO unit test for the property 'BankKey'
        }
        /// <summary>
        /// Test the property 'BeneficiaryAccount'
        /// </summary>
        [Test]
        public void BeneficiaryAccountTest()
        {
            // TODO unit test for the property 'BeneficiaryAccount'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Institution'
        /// </summary>
        [Test]
        public void InstitutionTest()
        {
            // TODO unit test for the property 'Institution'
        }
        /// <summary>
        /// Test the property 'KindOfRelationship'
        /// </summary>
        [Test]
        public void KindOfRelationshipTest()
        {
            // TODO unit test for the property 'KindOfRelationship'
        }
        /// <summary>
        /// Test the property 'NumericReferenceSpei'
        /// </summary>
        [Test]
        public void NumericReferenceSpeiTest()
        {
            // TODO unit test for the property 'NumericReferenceSpei'
        }
        /// <summary>
        /// Test the property 'PaymentConceptSpei'
        /// </summary>
        [Test]
        public void PaymentConceptSpeiTest()
        {
            // TODO unit test for the property 'PaymentConceptSpei'
        }
        /// <summary>
        /// Test the property 'Person'
        /// </summary>
        [Test]
        public void PersonTest()
        {
            // TODO unit test for the property 'Person'
        }
        /// <summary>
        /// Test the property 'Relationship'
        /// </summary>
        [Test]
        public void RelationshipTest()
        {
            // TODO unit test for the property 'Relationship'
        }
        /// <summary>
        /// Test the property 'Rfc'
        /// </summary>
        [Test]
        public void RfcTest()
        {
            // TODO unit test for the property 'Rfc'
        }

    }

}
