/* 
 * Wire4RestAPI
 *
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing BalanceListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BalanceListResponseTests
    {
        // TODO uncomment below to declare an instance variable for BalanceListResponse
        //private BalanceListResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BalanceListResponse
            //instance = new BalanceListResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BalanceListResponse
        /// </summary>
        [Test]
        public void BalanceListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BalanceListResponse
            //Assert.IsInstanceOfType<BalanceListResponse> (instance, "variable 'instance' is a BalanceListResponse");
        }


        /// <summary>
        /// Test the property 'Balances'
        /// </summary>
        [Test]
        public void BalancesTest()
        {
            // TODO unit test for the property 'Balances'
        }

    }

}
