/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing BeneficiaryInstitution
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeneficiaryInstitutionTests
    {
        // TODO uncomment below to declare an instance variable for BeneficiaryInstitution
        //private BeneficiaryInstitution instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeneficiaryInstitution
            //instance = new BeneficiaryInstitution();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeneficiaryInstitution
        /// </summary>
        [Test]
        public void BeneficiaryInstitutionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeneficiaryInstitution
            //Assert.IsInstanceOfType<BeneficiaryInstitution> (instance, "variable 'instance' is a BeneficiaryInstitution");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
