/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing BeneficiariesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeneficiariesResponseTests
    {
        // TODO uncomment below to declare an instance variable for BeneficiariesResponse
        //private BeneficiariesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeneficiariesResponse
            //instance = new BeneficiariesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeneficiariesResponse
        /// </summary>
        [Test]
        public void BeneficiariesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeneficiariesResponse
            //Assert.IsInstanceOfType<BeneficiariesResponse> (instance, "variable 'instance' is a BeneficiariesResponse");
        }


        /// <summary>
        /// Test the property 'Beneficiaries'
        /// </summary>
        [Test]
        public void BeneficiariesTest()
        {
            // TODO unit test for the property 'Beneficiaries'
        }

    }

}
