/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing CepResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CepResponseTests
    {
        // TODO uncomment below to declare an instance variable for CepResponse
        //private CepResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CepResponse
            //instance = new CepResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CepResponse
        /// </summary>
        [Test]
        public void CepResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CepResponse
            //Assert.IsInstanceOfType<CepResponse> (instance, "variable 'instance' is a CepResponse");
        }


        /// <summary>
        /// Test the property 'AccountBeneficiary'
        /// </summary>
        [Test]
        public void AccountBeneficiaryTest()
        {
            // TODO unit test for the property 'AccountBeneficiary'
        }
        /// <summary>
        /// Test the property 'AccountSender'
        /// </summary>
        [Test]
        public void AccountSenderTest()
        {
            // TODO unit test for the property 'AccountSender'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Test]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'BeneficiaryBankKey'
        /// </summary>
        [Test]
        public void BeneficiaryBankKeyTest()
        {
            // TODO unit test for the property 'BeneficiaryBankKey'
        }
        /// <summary>
        /// Test the property 'BeneficiaryName'
        /// </summary>
        [Test]
        public void BeneficiaryNameTest()
        {
            // TODO unit test for the property 'BeneficiaryName'
        }
        /// <summary>
        /// Test the property 'BeneficiaryRfc'
        /// </summary>
        [Test]
        public void BeneficiaryRfcTest()
        {
            // TODO unit test for the property 'BeneficiaryRfc'
        }
        /// <summary>
        /// Test the property 'CadenaOriginal'
        /// </summary>
        [Test]
        public void CadenaOriginalTest()
        {
            // TODO unit test for the property 'CadenaOriginal'
        }
        /// <summary>
        /// Test the property 'CaptureDate'
        /// </summary>
        [Test]
        public void CaptureDateTest()
        {
            // TODO unit test for the property 'CaptureDate'
        }
        /// <summary>
        /// Test the property 'CertificateSerialNumber'
        /// </summary>
        [Test]
        public void CertificateSerialNumberTest()
        {
            // TODO unit test for the property 'CertificateSerialNumber'
        }
        /// <summary>
        /// Test the property 'ClaveRastreo'
        /// </summary>
        [Test]
        public void ClaveRastreoTest()
        {
            // TODO unit test for the property 'ClaveRastreo'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Iva'
        /// </summary>
        [Test]
        public void IvaTest()
        {
            // TODO unit test for the property 'Iva'
        }
        /// <summary>
        /// Test the property 'OperationDate'
        /// </summary>
        [Test]
        public void OperationDateTest()
        {
            // TODO unit test for the property 'OperationDate'
        }
        /// <summary>
        /// Test the property 'OperationDateCep'
        /// </summary>
        [Test]
        public void OperationDateCepTest()
        {
            // TODO unit test for the property 'OperationDateCep'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'SenderBankKey'
        /// </summary>
        [Test]
        public void SenderBankKeyTest()
        {
            // TODO unit test for the property 'SenderBankKey'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Test]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'SenderRfc'
        /// </summary>
        [Test]
        public void SenderRfcTest()
        {
            // TODO unit test for the property 'SenderRfc'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'UrlZip'
        /// </summary>
        [Test]
        public void UrlZipTest()
        {
            // TODO unit test for the property 'UrlZip'
        }

    }

}
