/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing CodiCodeQrResponseDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CodiCodeQrResponseDTOTests
    {
        // TODO uncomment below to declare an instance variable for CodiCodeQrResponseDTO
        //private CodiCodeQrResponseDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CodiCodeQrResponseDTO
            //instance = new CodiCodeQrResponseDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CodiCodeQrResponseDTO
        /// </summary>
        [Test]
        public void CodiCodeQrResponseDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CodiCodeQrResponseDTO
            //Assert.IsInstanceOfType<CodiCodeQrResponseDTO> (instance, "variable 'instance' is a CodiCodeQrResponseDTO");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BarcodeBase64'
        /// </summary>
        [Test]
        public void BarcodeBase64Test()
        {
            // TODO unit test for the property 'BarcodeBase64'
        }
        /// <summary>
        /// Test the property 'BarcodeUrl'
        /// </summary>
        [Test]
        public void BarcodeUrlTest()
        {
            // TODO unit test for the property 'BarcodeUrl'
        }
        /// <summary>
        /// Test the property 'Concept'
        /// </summary>
        [Test]
        public void ConceptTest()
        {
            // TODO unit test for the property 'Concept'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
