/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing DepositAuthorizationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DepositAuthorizationRequestTests
    {
        // TODO uncomment below to declare an instance variable for DepositAuthorizationRequest
        //private DepositAuthorizationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DepositAuthorizationRequest
            //instance = new DepositAuthorizationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DepositAuthorizationRequest
        /// </summary>
        [Test]
        public void DepositAuthorizationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DepositAuthorizationRequest
            //Assert.IsInstanceOfType<DepositAuthorizationRequest> (instance, "variable 'instance' is a DepositAuthorizationRequest");
        }


        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Webhook'
        /// </summary>
        [Test]
        public void WebhookTest()
        {
            // TODO unit test for the property 'Webhook'
        }
        /// <summary>
        /// Test the property 'WhUuid'
        /// </summary>
        [Test]
        public void WhUuidTest()
        {
            // TODO unit test for the property 'WhUuid'
        }

    }

}
