/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing MessageDepositReceived
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageDepositReceivedTests
    {
        // TODO uncomment below to declare an instance variable for MessageDepositReceived
        //private MessageDepositReceived instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageDepositReceived
            //instance = new MessageDepositReceived();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageDepositReceived
        /// </summary>
        [Test]
        public void MessageDepositReceivedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageDepositReceived
            //Assert.IsInstanceOfType<MessageDepositReceived> (instance, "variable 'instance' is a MessageDepositReceived");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BeneficiaryAccount'
        /// </summary>
        [Test]
        public void BeneficiaryAccountTest()
        {
            // TODO unit test for the property 'BeneficiaryAccount'
        }
        /// <summary>
        /// Test the property 'BeneficiaryName'
        /// </summary>
        [Test]
        public void BeneficiaryNameTest()
        {
            // TODO unit test for the property 'BeneficiaryName'
        }
        /// <summary>
        /// Test the property 'BeneficiaryRfc'
        /// </summary>
        [Test]
        public void BeneficiaryRfcTest()
        {
            // TODO unit test for the property 'BeneficiaryRfc'
        }
        /// <summary>
        /// Test the property 'Cep'
        /// </summary>
        [Test]
        public void CepTest()
        {
            // TODO unit test for the property 'Cep'
        }
        /// <summary>
        /// Test the property 'ClaveRastreo'
        /// </summary>
        [Test]
        public void ClaveRastreoTest()
        {
            // TODO unit test for the property 'ClaveRastreo'
        }
        /// <summary>
        /// Test the property 'ConfirmDate'
        /// </summary>
        [Test]
        public void ConfirmDateTest()
        {
            // TODO unit test for the property 'ConfirmDate'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'DepositDate'
        /// </summary>
        [Test]
        public void DepositDateTest()
        {
            // TODO unit test for the property 'DepositDate'
        }
        /// <summary>
        /// Test the property 'Depositant'
        /// </summary>
        [Test]
        public void DepositantTest()
        {
            // TODO unit test for the property 'Depositant'
        }
        /// <summary>
        /// Test the property 'DepositantAlias'
        /// </summary>
        [Test]
        public void DepositantAliasTest()
        {
            // TODO unit test for the property 'DepositantAlias'
        }
        /// <summary>
        /// Test the property 'DepositantClabe'
        /// </summary>
        [Test]
        public void DepositantClabeTest()
        {
            // TODO unit test for the property 'DepositantClabe'
        }
        /// <summary>
        /// Test the property 'DepositantEmail'
        /// </summary>
        [Test]
        public void DepositantEmailTest()
        {
            // TODO unit test for the property 'DepositantEmail'
        }
        /// <summary>
        /// Test the property 'DepositantRfc'
        /// </summary>
        [Test]
        public void DepositantRfcTest()
        {
            // TODO unit test for the property 'DepositantRfc'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MonexDescription'
        /// </summary>
        [Test]
        public void MonexDescriptionTest()
        {
            // TODO unit test for the property 'MonexDescription'
        }
        /// <summary>
        /// Test the property 'MonexTransactionId'
        /// </summary>
        [Test]
        public void MonexTransactionIdTest()
        {
            // TODO unit test for the property 'MonexTransactionId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Test]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'ReturnIdInstruction'
        /// </summary>
        [Test]
        public void ReturnIdInstructionTest()
        {
            // TODO unit test for the property 'ReturnIdInstruction'
        }
        /// <summary>
        /// Test the property 'SenderAccount'
        /// </summary>
        [Test]
        public void SenderAccountTest()
        {
            // TODO unit test for the property 'SenderAccount'
        }
        /// <summary>
        /// Test the property 'SenderBank'
        /// </summary>
        [Test]
        public void SenderBankTest()
        {
            // TODO unit test for the property 'SenderBank'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Test]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'SenderRfc'
        /// </summary>
        [Test]
        public void SenderRfcTest()
        {
            // TODO unit test for the property 'SenderRfc'
        }

    }

}
