/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing PaymentsSpeiAndSpidRequestId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentsSpeiAndSpidRequestIdTests
    {
        // TODO uncomment below to declare an instance variable for PaymentsSpeiAndSpidRequestId
        //private PaymentsSpeiAndSpidRequestId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentsSpeiAndSpidRequestId
            //instance = new PaymentsSpeiAndSpidRequestId();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentsSpeiAndSpidRequestId
        /// </summary>
        [Test]
        public void PaymentsSpeiAndSpidRequestIdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentsSpeiAndSpidRequestId
            //Assert.IsInstanceOfType<PaymentsSpeiAndSpidRequestId> (instance, "variable 'instance' is a PaymentsSpeiAndSpidRequestId");
        }


        /// <summary>
        /// Test the property 'AuthorizationDate'
        /// </summary>
        [Test]
        public void AuthorizationDateTest()
        {
            // TODO unit test for the property 'AuthorizationDate'
        }
        /// <summary>
        /// Test the property 'RequestDate'
        /// </summary>
        [Test]
        public void RequestDateTest()
        {
            // TODO unit test for the property 'RequestDate'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'Spei'
        /// </summary>
        [Test]
        public void SpeiTest()
        {
            // TODO unit test for the property 'Spei'
        }
        /// <summary>
        /// Test the property 'Spid'
        /// </summary>
        [Test]
        public void SpidTest()
        {
            // TODO unit test for the property 'Spid'
        }

    }

}
