/* 
 * Wire4RestAPI
 *
 * Referencia de API. La API de Wire4 está organizada en torno a REST
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing ServiceBanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceBankingTests
    {
        // TODO uncomment below to declare an instance variable for ServiceBanking
        //private ServiceBanking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceBanking
            //instance = new ServiceBanking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceBanking
        /// </summary>
        [Test]
        public void ServiceBankingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceBanking
            //Assert.IsInstanceOfType<ServiceBanking> (instance, "variable 'instance' is a ServiceBanking");
        }


        /// <summary>
        /// Test the property 'Spei'
        /// </summary>
        [Test]
        public void SpeiTest()
        {
            // TODO unit test for the property 'Spei'
        }
        /// <summary>
        /// Test the property 'Spid'
        /// </summary>
        [Test]
        public void SpidTest()
        {
            // TODO unit test for the property 'Spid'
        }

    }

}
