/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing TransactionsRegister
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionsRegisterTests
    {
        // TODO uncomment below to declare an instance variable for TransactionsRegister
        //private TransactionsRegister instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionsRegister
            //instance = new TransactionsRegister();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionsRegister
        /// </summary>
        [Test]
        public void TransactionsRegisterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionsRegister
            //Assert.IsInstanceOfType<TransactionsRegister> (instance, "variable 'instance' is a TransactionsRegister");
        }


        /// <summary>
        /// Test the property 'CancelReturnUrl'
        /// </summary>
        [Test]
        public void CancelReturnUrlTest()
        {
            // TODO unit test for the property 'CancelReturnUrl'
        }
        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Test]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }
        /// <summary>
        /// Test the property 'Spei'
        /// </summary>
        [Test]
        public void SpeiTest()
        {
            // TODO unit test for the property 'Spei'
        }
        /// <summary>
        /// Test the property 'Spid'
        /// </summary>
        [Test]
        public void SpidTest()
        {
            // TODO unit test for the property 'Spid'
        }

    }

}
