/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Wire4.Api;
using MX.Wire4.Model;
using MX.Wire4.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Wire4.Test
{
    /// <summary>
    ///  Class for testing UseServiceBanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UseServiceBankingTests
    {
        // TODO uncomment below to declare an instance variable for UseServiceBanking
        //private UseServiceBanking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UseServiceBanking
            //instance = new UseServiceBanking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UseServiceBanking
        /// </summary>
        [Test]
        public void UseServiceBankingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UseServiceBanking
            //Assert.IsInstanceOfType<UseServiceBanking> (instance, "variable 'instance' is a UseServiceBanking");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Use'
        /// </summary>
        [Test]
        public void UseTest()
        {
            // TODO unit test for the property 'Use'
        }

    }

}
