/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = MX.Wire4.Client.SwaggerDateConverter;

namespace MX.Wire4.Model
{
    /// <summary>
    /// Objeto que contiene información de la cuenta
    /// </summary>
    [DataContract]
        public partial class Account :  IEquatable<Account>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Account" /> class.
        /// </summary>
        /// <param name="amountLimit">Monto límite permitido registrado para la cuenta (required).</param>
        /// <param name="bankKey">Clave del banco, es requerido en caso de que la cuenta del beneficiario sea un número de celular.</param>
        /// <param name="beneficiaryAccount">Cuenta del beneficiario, podría ser teléfono celular, TDD o cuenta CLABE (required).</param>
        /// <param name="email">Lista de email&#x27;s, este dato es opcional.</param>
        /// <param name="institution">institution.</param>
        /// <param name="kindOfRelationship">Tipo de relación con el propietario de la cuenta, para registrar una cuenta este valor se debe obtener  del recurso relationships. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta. (required).</param>
        /// <param name="numericReferenceSpei">Referencia numérica a utilizar cuando se realice una transferencia y no se especifique una referencia.</param>
        /// <param name="paymentConceptSpei">Concepto de pago a utilizar cuando se realice una transferencia y no se especifique un concepto.</param>
        /// <param name="person">person.</param>
        /// <param name="relationship">Relación con el propietario de la cuenta, para registrar una cuenta este valor se debe obtener  del recurso relationships. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta. (required).</param>
        /// <param name="rfc">Registro federal de contribuyentes de la persona o institución propietaria de la cuenta. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta. (required).</param>
        public Account(decimal? amountLimit = default(decimal?), string bankKey = default(string), string beneficiaryAccount = default(string), List<string> email = default(List<string>), BeneficiaryInstitution institution = default(BeneficiaryInstitution), string kindOfRelationship = default(string), string numericReferenceSpei = default(string), string paymentConceptSpei = default(string), Person person = default(Person), string relationship = default(string), string rfc = default(string))
        {
            // to ensure "amountLimit" is required (not null)
            if (amountLimit == null)
            {
                throw new InvalidDataException("amountLimit is a required property for Account and cannot be null");
            }
            else
            {
                this.AmountLimit = amountLimit;
            }
            // to ensure "beneficiaryAccount" is required (not null)
            if (beneficiaryAccount == null)
            {
                throw new InvalidDataException("beneficiaryAccount is a required property for Account and cannot be null");
            }
            else
            {
                this.BeneficiaryAccount = beneficiaryAccount;
            }
            // to ensure "kindOfRelationship" is required (not null)
            if (kindOfRelationship == null)
            {
                throw new InvalidDataException("kindOfRelationship is a required property for Account and cannot be null");
            }
            else
            {
                this.KindOfRelationship = kindOfRelationship;
            }
            // to ensure "relationship" is required (not null)
            if (relationship == null)
            {
                throw new InvalidDataException("relationship is a required property for Account and cannot be null");
            }
            else
            {
                this.Relationship = relationship;
            }
            // to ensure "rfc" is required (not null)
            if (rfc == null)
            {
                throw new InvalidDataException("rfc is a required property for Account and cannot be null");
            }
            else
            {
                this.Rfc = rfc;
            }
            this.BankKey = bankKey;
            this.Email = email;
            this.Institution = institution;
            this.NumericReferenceSpei = numericReferenceSpei;
            this.PaymentConceptSpei = paymentConceptSpei;
            this.Person = person;
        }
        
        /// <summary>
        /// Monto límite permitido registrado para la cuenta
        /// </summary>
        /// <value>Monto límite permitido registrado para la cuenta</value>
        [DataMember(Name="amount_limit", EmitDefaultValue=false)]
        public decimal? AmountLimit { get; set; }

        /// <summary>
        /// Clave del banco, es requerido en caso de que la cuenta del beneficiario sea un número de celular
        /// </summary>
        /// <value>Clave del banco, es requerido en caso de que la cuenta del beneficiario sea un número de celular</value>
        [DataMember(Name="bank_key", EmitDefaultValue=false)]
        public string BankKey { get; set; }

        /// <summary>
        /// Cuenta del beneficiario, podría ser teléfono celular, TDD o cuenta CLABE
        /// </summary>
        /// <value>Cuenta del beneficiario, podría ser teléfono celular, TDD o cuenta CLABE</value>
        [DataMember(Name="beneficiary_account", EmitDefaultValue=false)]
        public string BeneficiaryAccount { get; set; }

        /// <summary>
        /// Lista de email&#x27;s, este dato es opcional
        /// </summary>
        /// <value>Lista de email&#x27;s, este dato es opcional</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public List<string> Email { get; set; }

        /// <summary>
        /// Gets or Sets Institution
        /// </summary>
        [DataMember(Name="institution", EmitDefaultValue=false)]
        public BeneficiaryInstitution Institution { get; set; }

        /// <summary>
        /// Tipo de relación con el propietario de la cuenta, para registrar una cuenta este valor se debe obtener  del recurso relationships. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta.
        /// </summary>
        /// <value>Tipo de relación con el propietario de la cuenta, para registrar una cuenta este valor se debe obtener  del recurso relationships. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta.</value>
        [DataMember(Name="kind_of_relationship", EmitDefaultValue=false)]
        public string KindOfRelationship { get; set; }

        /// <summary>
        /// Referencia numérica a utilizar cuando se realice una transferencia y no se especifique una referencia
        /// </summary>
        /// <value>Referencia numérica a utilizar cuando se realice una transferencia y no se especifique una referencia</value>
        [DataMember(Name="numeric_reference_spei", EmitDefaultValue=false)]
        public string NumericReferenceSpei { get; set; }

        /// <summary>
        /// Concepto de pago a utilizar cuando se realice una transferencia y no se especifique un concepto
        /// </summary>
        /// <value>Concepto de pago a utilizar cuando se realice una transferencia y no se especifique un concepto</value>
        [DataMember(Name="payment_concept_spei", EmitDefaultValue=false)]
        public string PaymentConceptSpei { get; set; }

        /// <summary>
        /// Gets or Sets Person
        /// </summary>
        [DataMember(Name="person", EmitDefaultValue=false)]
        public Person Person { get; set; }

        /// <summary>
        /// Relación con el propietario de la cuenta, para registrar una cuenta este valor se debe obtener  del recurso relationships. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta.
        /// </summary>
        /// <value>Relación con el propietario de la cuenta, para registrar una cuenta este valor se debe obtener  del recurso relationships. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta.</value>
        [DataMember(Name="relationship", EmitDefaultValue=false)]
        public string Relationship { get; set; }

        /// <summary>
        /// Registro federal de contribuyentes de la persona o institución propietaria de la cuenta. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta.
        /// </summary>
        /// <value>Registro federal de contribuyentes de la persona o institución propietaria de la cuenta. &lt;br&gt; Nota: Si en la respuesta de Monex esta propiedad es nula, tampoco estará presente en esta respuesta.</value>
        [DataMember(Name="rfc", EmitDefaultValue=false)]
        public string Rfc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Account {\n");
            sb.Append("  AmountLimit: ").Append(AmountLimit).Append("\n");
            sb.Append("  BankKey: ").Append(BankKey).Append("\n");
            sb.Append("  BeneficiaryAccount: ").Append(BeneficiaryAccount).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Institution: ").Append(Institution).Append("\n");
            sb.Append("  KindOfRelationship: ").Append(KindOfRelationship).Append("\n");
            sb.Append("  NumericReferenceSpei: ").Append(NumericReferenceSpei).Append("\n");
            sb.Append("  PaymentConceptSpei: ").Append(PaymentConceptSpei).Append("\n");
            sb.Append("  Person: ").Append(Person).Append("\n");
            sb.Append("  Relationship: ").Append(Relationship).Append("\n");
            sb.Append("  Rfc: ").Append(Rfc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Account);
        }

        /// <summary>
        /// Returns true if Account instances are equal
        /// </summary>
        /// <param name="input">Instance of Account to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Account input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AmountLimit == input.AmountLimit ||
                    (this.AmountLimit != null &&
                    this.AmountLimit.Equals(input.AmountLimit))
                ) && 
                (
                    this.BankKey == input.BankKey ||
                    (this.BankKey != null &&
                    this.BankKey.Equals(input.BankKey))
                ) && 
                (
                    this.BeneficiaryAccount == input.BeneficiaryAccount ||
                    (this.BeneficiaryAccount != null &&
                    this.BeneficiaryAccount.Equals(input.BeneficiaryAccount))
                ) && 
                (
                    this.Email == input.Email ||
                    this.Email != null &&
                    input.Email != null &&
                    this.Email.SequenceEqual(input.Email)
                ) && 
                (
                    this.Institution == input.Institution ||
                    (this.Institution != null &&
                    this.Institution.Equals(input.Institution))
                ) && 
                (
                    this.KindOfRelationship == input.KindOfRelationship ||
                    (this.KindOfRelationship != null &&
                    this.KindOfRelationship.Equals(input.KindOfRelationship))
                ) && 
                (
                    this.NumericReferenceSpei == input.NumericReferenceSpei ||
                    (this.NumericReferenceSpei != null &&
                    this.NumericReferenceSpei.Equals(input.NumericReferenceSpei))
                ) && 
                (
                    this.PaymentConceptSpei == input.PaymentConceptSpei ||
                    (this.PaymentConceptSpei != null &&
                    this.PaymentConceptSpei.Equals(input.PaymentConceptSpei))
                ) && 
                (
                    this.Person == input.Person ||
                    (this.Person != null &&
                    this.Person.Equals(input.Person))
                ) && 
                (
                    this.Relationship == input.Relationship ||
                    (this.Relationship != null &&
                    this.Relationship.Equals(input.Relationship))
                ) && 
                (
                    this.Rfc == input.Rfc ||
                    (this.Rfc != null &&
                    this.Rfc.Equals(input.Rfc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AmountLimit != null)
                    hashCode = hashCode * 59 + this.AmountLimit.GetHashCode();
                if (this.BankKey != null)
                    hashCode = hashCode * 59 + this.BankKey.GetHashCode();
                if (this.BeneficiaryAccount != null)
                    hashCode = hashCode * 59 + this.BeneficiaryAccount.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Institution != null)
                    hashCode = hashCode * 59 + this.Institution.GetHashCode();
                if (this.KindOfRelationship != null)
                    hashCode = hashCode * 59 + this.KindOfRelationship.GetHashCode();
                if (this.NumericReferenceSpei != null)
                    hashCode = hashCode * 59 + this.NumericReferenceSpei.GetHashCode();
                if (this.PaymentConceptSpei != null)
                    hashCode = hashCode * 59 + this.PaymentConceptSpei.GetHashCode();
                if (this.Person != null)
                    hashCode = hashCode * 59 + this.Person.GetHashCode();
                if (this.Relationship != null)
                    hashCode = hashCode * 59 + this.Relationship.GetHashCode();
                if (this.Rfc != null)
                    hashCode = hashCode * 59 + this.Rfc.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
