/* 
 * Wire4RestAPI
 *
 * Referencia de la API de Wire4
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = MX.Wire4.Client.SwaggerDateConverter;

namespace MX.Wire4.Model
{
    /// <summary>
    /// Servicio con el que se transacciona en la subscripción
    /// </summary>
    [DataContract]
        public partial class ServiceBanking :  IEquatable<ServiceBanking>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceBanking" /> class.
        /// </summary>
        /// <param name="spei">spei.</param>
        /// <param name="spid">spid.</param>
        public ServiceBanking(UseServiceBanking spei = default(UseServiceBanking), UseServiceBanking spid = default(UseServiceBanking))
        {
            this.Spei = spei;
            this.Spid = spid;
        }
        
        /// <summary>
        /// Gets or Sets Spei
        /// </summary>
        [DataMember(Name="spei", EmitDefaultValue=false)]
        public UseServiceBanking Spei { get; set; }

        /// <summary>
        /// Gets or Sets Spid
        /// </summary>
        [DataMember(Name="spid", EmitDefaultValue=false)]
        public UseServiceBanking Spid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceBanking {\n");
            sb.Append("  Spei: ").Append(Spei).Append("\n");
            sb.Append("  Spid: ").Append(Spid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ServiceBanking);
        }

        /// <summary>
        /// Returns true if ServiceBanking instances are equal
        /// </summary>
        /// <param name="input">Instance of ServiceBanking to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceBanking input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Spei == input.Spei ||
                    (this.Spei != null &&
                    this.Spei.Equals(input.Spei))
                ) && 
                (
                    this.Spid == input.Spid ||
                    (this.Spid != null &&
                    this.Spid.Equals(input.Spid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Spei != null)
                    hashCode = hashCode * 59 + this.Spei.GetHashCode();
                if (this.Spid != null)
                    hashCode = hashCode * 59 + this.Spid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
